services:
  personnelmanagement:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - 'DatabaseSettings__DefaultConnection=Server=sqlserver;Database=PersonnelManagement;User Id=sa;Password=Hau2004@;TrustServerCertificate=true' 
    ports:
      - "3030:8080"
      - "3031:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro